### ISSUE TITLE
MapGL doesn't work on chromium 41.0.2272.76 Ubuntu 14.04 (64-bit) 

### ISSUE THREAD

**Issue by jurrew27** [ArnoldSwaggernegger/ariana#42]
TypeError: Cannot read property 'enable' of null
    at new RenderEngine (renderEngine.js:620)
    at Scope.$scope.startEngine (app.js:45)
    at new <anonymous> (content.logic.js:37)
    at invoke (angular.js:4426)
    at Object.instantiate (angular.js:4434)
    at angular.js:8960
    at angular-ui-router.js:4018
    at invokeLinkFn (angular.js:8604)
    at nodeLinkFn (angular.js:8113)
    at compositeLinkFn (angular.js:7514)
angular.js:12221 TypeError: Cannot read property 'createTexture' of null
    at new DrawBuffer (http://localhost:3000/js/renderEngine.js:279:31)
    at new RenderEngine (http://localhost:3000/js/renderEngine.js:627:28)
    at Scope.$scope.startEngine (http://localhost:3000/js/app.js:45:35)
    at new <anonymous> (http://localhost:3000/js/content.logic.js:37:12)
    at invoke (http://localhost:3000/vendor/angular.js:4426:17)
    at Object.instantiate (http://localhost:3000/vendor/angular.js:4434:27)
    at http://localhost:3000/vendor/angular.js:8960:28
    at http://localhost:3000/vendor/angular-ui-router.js:4018:28
    at invokeLinkFn (http://localhost:3000/vendor/angular.js:8604:9)
    at nodeLinkFn (http://localhost:3000/vendor/angular.js:8113:11) <div ui-view="content" class="ng-scope">

**Comment by mathijs727** [comment]
ik kan niet magisch opeens WebGL support toevoegen aan je laptop. ;(
