### ISSUE TITLE
newLayerFromImage doesn't work

### ISSUE THREAD

**Issue by jurrew27** [ArnoldSwaggernegger/ariana#43]
TypeError: Cannot read property 'getWebGLRenderingContext' of null
    at $rootScope.newLayerFromImage (http://localhost:3000/js/app.js:51:64)
    at Array.forEach (native)
    at Scope.$scope.upload (http://localhost:3000/js/upload.logic.js:11:32)
    at fn (eval at <anonymous> (http://localhost:3000/vendor/angular.js:13036:15), <anonymous>:2:209)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://localhost:3000/vendor/angular.js:23090:17)
    at Scope.$get.Scope.$eval (http://localhost:3000/vendor/angular.js:15719:28)
    at Scope.$get.Scope.$apply (http://localhost:3000/vendor/angular.js:15818:23)
    at HTMLButtonElement.<anonymous> (http://localhost:3000/vendor/angular.js:23095:23)
    at HTMLButtonElement.jQuery.event.dispatch (http://localhost:3000/vendor/jquery.js:4435:9)
    at HTMLButtonElement.jQuery.event.add.elemData.handle (http://localhost:3000/vendor/jquery.js:4121:28)angular.js:12221 (anonymous function)angular.js:9055 $getangular.js:15820 $get.Scope.$applyangular.js:23095 (anonymous function)jquery.js:4435 jQuery.event.dispatchjquery.js:4121 jQuery.event.add.elemData.handle

**Comment by TengenJulian** [comment]
It works if you add an Image :')

**Comment by jurrew27** [comment]
Lol vergeten

Op ma 8 jun. 2015 19:02 schreef TengenJulian <notifications@github.com>:
