### ISSUE TITLE
Download only works once

### ISSUE THREAD

**Issue by sjerdo** [ArnoldSwaggernegger/ariana#79]
If you try to download the image the second time, an error occurs.

```
TypeError: Cannot read property '0' of undefined
    at Object.mat3.multiply (http://localhost:3000/js/gl-matrix.js:2614:16)
    at ImageLayer.render (http://localhost:3000/js/renderEngine.js:1291:14)
    at RenderEngine.renderIndices (http://localhost:3000/js/renderEngine.js:1434:19)
    at RenderEngine.renderIndicesToImg (http://localhost:3000/js/renderEngine.js:1441:14)
    at RenderEngine.renderToImg (http://localhost:3000/js/renderEngine.js:1451:21)
    at Scope.$scope.saveImage (http://localhost:3000/js/toolbar.logic.js:23:45)
    at $parseFunctionCall (http://localhost:3000/vendor/angular.js:12158:18)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://localhost:3000/vendor/angular.js:22645:17)
    at Scope.$get.Scope.$eval (http://localhost:3000/vendor/angular.js:14200:28)
    at Scope.$get.Scope.$apply (http://localhost:3000/vendor/angular.js:14298:23)
```

**Comment by sjerdo** [comment]
fixed in commit 1086efe
